name: Run All Tests
on:
  push:
    branches: [create_workflows]


jobs: 
  test_and_build:
    name: Use pre-built setup Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Regenerate Pipfile.lock
        run: |
          pipenv lock
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest

  build_and_upload:
    needs: [test_and_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pass
        run: |
          echo "hello world"
          
    