name: Build and test on mac
on:
  push:
    branches: [final_workflow]
  pull_request:
    branches: [main]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.11"
      - name: Build package
        run: |
          pipenv install build
          pipenv run python -m build .

  run_pytest:
    needs: [build-mac]
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Regenerate lock file
        run: |
          pipenv lock
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      
      - name: show dependencies
        run: |
          pipenv run pip list
          echo "****************"
          pipenv graph
            
      - name: Test with pytest
        run: |
          pipenv run python -m pytest
      
      