name: CI / CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pip install --upgrade pipenv
      - name: Install Python, pipenv, and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Debug Information
        run: |
          python --version
          pip --version
          pipenv --venv
          pipenv graph

      - name: Check virtual environment
          run: pipenv --venv

      - name: Install dependencies
          run: pipenv install

        - name: Install pytest
          run: pipenv install pytest

      - name: Test with pytest
        run: pipenv run pytest -v

  build_and_upload:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pass
        run: |
          echo "hello world"

          
    