name: Build and test on win
on:
  push:
    branches: [final_workflow]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - name: Regen pipfile.lock
        run: pipenv lock
        shell: bash

      - name: Turn on 'editable' mode, install dependencies
        run: |
          pipenv install -e .
          pipenv run pip install kivy pygame
      
      - name: Run unit tests
        run: |
          pipenv run -v python -m pytest
      
      